png(filename="plot4.png")
par(mfrow=c(2,2),mar=c(4.1,4.1,2.1,2.1),oma=c(0,0,0,0))
x<-read.csv("household_power_consumption.txt",nrow=85000,sep=";")
y<-x[(x$Date=="1/2/2007"|x$Date=="2/2/2007"),]
a<-as.Date(y$Date,format="%d/%m/%Y")
b<-as.character(y$Time)
c<-paste(a,b)
d<-strptime(c,format="%Y-%m-%d %H:%M:%S")
sm1<-as.numeric(as.character((y[,7])))
sm2<-as.numeric(as.character((y[,8])))
sm3<-as.numeric(as.character((y[,9])))
plot(d,as.numeric(as.character(y[,3])),type="l",xlab="",ylab="Global Active Power(kilowatts)")
plot(d,as.numeric(as.character(y[,5])),type="l",xlab="datetime",ylab="voltage")
plot(d,sm1,type="l",xlab="",ylab="Energy sub metering",col="black")
lines(d,sm2,col="red")
lines(d,sm3,col="blue")
legend("topright",lty=1,bty="n",col=c("black","red","blue"),legend=c("sub_metering_1","sub_metering_2","sub_metering_3"))
plot(d,as.numeric(as.character(y[,4])),type="l",xlab="datetime",ylab="Global Reactive Power(kilowatts)")
dev.off()