x<-read.csv("household_power_consumption.txt",nrow=85000,sep=";")
y<-x[(x$Date=="1/2/2007"|x$Date=="2/2/2007"),]
a<-as.Date(y$Date,format="%d/%m/%Y")
b<-as.character(y$Time)
c<-paste(a,b)
d<-strptime(c,format="%Y-%m-%d %H:%M:%S")
sm1<-as.numeric(as.character((y[,7])))
sm2<-as.numeric(as.character((y[,8])))
sm3<-as.numeric(as.character((y[,9])))
png(filename="plot3.png")
plot(d,sm1,type="l",xlab="",ylab="Energy sub metering",col="black")
lines(d,sm2,col="red")
lines(d,sm3,col="blue")
legend("topright",lty=1,col=c("black","red","blue"),legend=c("sub_metering_1","sub_metering_2","sub_metering_3"))
dev.off()